version: "3"

services:
  db:
    platform: linux/x86_64 
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data